#!/bin/bash

# Open MCP Skills - Cognito Authentication Setup
# Creates Cognito User Pool, Domain, Resource Server, and App Clients:
#   - S2S (Service-to-Service) client for MCP API access (client_credentials flow)
#   - Frontend client for user login (authorization_code + PKCE, no secret)

set -e

REGION="${1:-us-east-1}"
PROJECT_NAME="openmcpskills"
FRONTEND_URL="${2:-https://mcp.openmcpskills.click}"

echo "================================================"
echo "Setting up Cognito Authentication"
echo "Project: $PROJECT_NAME"
echo "Region: $REGION"
echo "Frontend URL: $FRONTEND_URL"
echo "================================================"

# 1. Create User Pool
echo ""
echo "[1/6] Creating User Pool..."
POOL_RESPONSE=$(aws cognito-idp create-user-pool \
  --pool-name "${PROJECT_NAME}-auth-pool" \
  --auto-verified-attributes email \
  --admin-create-user-config AllowAdminCreateUserOnly=false \
  --policies '{"PasswordPolicy":{"MinimumLength":8,"RequireUppercase":true,"RequireLowercase":true,"RequireNumbers":true,"RequireSymbols":true}}' \
  --region $REGION)
POOL_ID=$(echo $POOL_RESPONSE | jq -r '.UserPool.Id')
echo "  User Pool ID: $POOL_ID"

# 2. Create Domain
echo ""
echo "[2/6] Creating Domain..."
DOMAIN_PREFIX="${PROJECT_NAME}-$(aws sts get-caller-identity --query Account --output text)"
aws cognito-idp create-user-pool-domain \
  --domain $DOMAIN_PREFIX \
  --user-pool-id $POOL_ID \
  --region $REGION
TOKEN_ENDPOINT="https://${DOMAIN_PREFIX}.auth.${REGION}.amazoncognito.com/oauth2/token"
echo "  Domain: $DOMAIN_PREFIX"
echo "  Token Endpoint: $TOKEN_ENDPOINT"

# 3. Create Resource Server (for S2S scopes)
echo ""
echo "[3/6] Creating Resource Server..."
RESOURCE_SERVER_IDENTIFIER="${PROJECT_NAME}-api"
aws cognito-idp create-resource-server \
  --user-pool-id $POOL_ID \
  --identifier $RESOURCE_SERVER_IDENTIFIER \
  --name "Open MCP Skills API" \
  --scopes \
    ScopeName=mcp,ScopeDescription="MCP protocol access" \
    ScopeName=admin,ScopeDescription="Admin access" \
    ScopeName=read,ScopeDescription="Read access" \
  --region $REGION
echo "  Resource Server: $RESOURCE_SERVER_IDENTIFIER"

# 4. Create S2S App Client (client_credentials flow, with secret)
echo ""
echo "[4/6] Creating S2S App Client..."
S2S_RESPONSE=$(aws cognito-idp create-user-pool-client \
  --user-pool-id $POOL_ID \
  --client-name "${PROJECT_NAME}-service-client" \
  --generate-secret \
  --allowed-o-auth-flows "client_credentials" \
  --allowed-o-auth-scopes \
    "${RESOURCE_SERVER_IDENTIFIER}/mcp" \
    "${RESOURCE_SERVER_IDENTIFIER}/read" \
  --allowed-o-auth-flows-user-pool-client \
  --region $REGION)
S2S_CLIENT_ID=$(echo $S2S_RESPONSE | jq -r '.UserPoolClient.ClientId')
S2S_CLIENT_SECRET=$(echo $S2S_RESPONSE | jq -r '.UserPoolClient.ClientSecret')
echo "  Client ID: $S2S_CLIENT_ID"
echo "  Client Secret: $S2S_CLIENT_SECRET"

# 5. Create Frontend App Client (authorization_code + PKCE, no secret)
echo ""
echo "[5/6] Creating Frontend App Client..."
FRONTEND_RESPONSE=$(aws cognito-idp create-user-pool-client \
  --user-pool-id $POOL_ID \
  --client-name "${PROJECT_NAME}-frontend" \
  --no-generate-secret \
  --explicit-auth-flows ALLOW_REFRESH_TOKEN_AUTH ALLOW_USER_SRP_AUTH \
  --supported-identity-providers COGNITO \
  --callback-urls "[\"${FRONTEND_URL}/\",\"http://localhost:5173/\"]" \
  --logout-urls "[\"${FRONTEND_URL}/login\",\"http://localhost:5173/login\"]" \
  --allowed-o-auth-flows code \
  --allowed-o-auth-scopes openid email profile \
  --allowed-o-auth-flows-user-pool-client \
  --region $REGION)
FRONTEND_CLIENT_ID=$(echo $FRONTEND_RESPONSE | jq -r '.UserPoolClient.ClientId')
echo "  Client ID: $FRONTEND_CLIENT_ID"

# 6. Test S2S token retrieval
echo ""
echo "[6/6] Testing S2S token retrieval..."
TOKEN_RESPONSE=$(curl -s -X POST "$TOKEN_ENDPOINT" \
  -H "Content-Type: application/x-www-form-urlencoded" \
  -u "${S2S_CLIENT_ID}:${S2S_CLIENT_SECRET}" \
  -d "grant_type=client_credentials&scope=${RESOURCE_SERVER_IDENTIFIER}/mcp ${RESOURCE_SERVER_IDENTIFIER}/read")
ACCESS_TOKEN=$(echo $TOKEN_RESPONSE | jq -r '.access_token')

if [ "$ACCESS_TOKEN" != "null" ] && [ -n "$ACCESS_TOKEN" ]; then
  echo "  S2S token obtained successfully!"
else
  echo "  WARNING: Failed to obtain S2S token"
  echo $TOKEN_RESPONSE | jq
fi

# Write cognito.env
cat > infrastructure/cognito.env << EOFENV
# Cognito Authentication Configuration
# Generated by setup_cognito.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)

# User Pool
COGNITO_USER_POOL_ID=$POOL_ID
COGNITO_REGION=$REGION
DOMAIN_PREFIX=$DOMAIN_PREFIX

# S2S (Service-to-Service) Authentication
COGNITO_ENABLED=true
COGNITO_TOKEN_ENDPOINT=$TOKEN_ENDPOINT
COGNITO_ALLOWED_CLIENT_IDS=
COGNITO_RESOURCE_SERVER=$RESOURCE_SERVER_IDENTIFIER
COGNITO_SCOPES=${RESOURCE_SERVER_IDENTIFIER}/mcp,${RESOURCE_SERVER_IDENTIFIER}/read

# S2S Test Credentials (first client — store securely)
COGNITO_CLIENT_ID=$S2S_CLIENT_ID
COGNITO_CLIENT_SECRET=$S2S_CLIENT_SECRET

# Frontend App Client (public, no secret)
COGNITO_FRONTEND_CLIENT_ID=$FRONTEND_CLIENT_ID
EOFENV

# Write amplify_outputs.json for frontend
cat > frontend/amplify_outputs.json << EOFJSON
{
  "version": "1.3",
  "auth": {
    "user_pool_id": "$POOL_ID",
    "user_pool_client_id": "$FRONTEND_CLIENT_ID",
    "aws_region": "$REGION",
    "password_policy": {
      "min_length": 8,
      "require_lowercase": true,
      "require_uppercase": true,
      "require_numbers": true,
      "require_symbols": true
    },
    "standard_required_attributes": [
      "email"
    ],
    "username_attributes": [
      "email"
    ],
    "user_verification_types": [
      "email"
    ],
    "unauthenticated_identities_enabled": false
  }
}
EOFJSON

echo ""
echo "================================================"
echo "Setup complete!"
echo "================================================"
echo ""
echo "Files written:"
echo "  - infrastructure/cognito.env (backend config + S2S credentials)"
echo "  - frontend/amplify_outputs.json (frontend Amplify config)"
echo ""
echo "Next steps:"
echo "  1. Copy Cognito settings to .env.deploy:"
echo "     COGNITO_ENABLED=true"
echo "     COGNITO_USER_POOL_ID=$POOL_ID"
echo "     COGNITO_REGION=$REGION"
echo "     COGNITO_ALLOWED_CLIENT_IDS="
echo "     COGNITO_TOKEN_ENDPOINT=$TOKEN_ENDPOINT"
echo "     COGNITO_SCOPES=${RESOURCE_SERVER_IDENTIFIER}/mcp,${RESOURCE_SERVER_IDENTIFIER}/read"
echo ""
echo "  2. Deploy backend and frontend"
echo ""
echo "  3. Test S2S auth: ./infrastructure/test_mcp_auth.sh"
echo ""
echo "  4. Additional S2S clients can be created from the frontend Settings page"
echo ""
